// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see library/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformLibrary",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformLibrary", targets: ["FeastMultiplatformLibrary"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformLibrary",
            url: "https://github.com/guardian/feast-multiplatform-library/releases/download/25.0.2/FeastMultiplatformLibrary.xcframework.zip",
            checksum:"c4eb1ac4d00942e6248b95dfc1d6b8158afcb634924aad56f7227665319152fd")
    ]
)