// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see library/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformLibrary",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformLibrary", targets: ["FeastMultiplatformLibrary"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformLibrary",
            url: "https://github.com/guardian/feast-multiplatform-library/releases/download/9.0.2/FeastMultiplatformLibrary.xcframework.zip",
            checksum:"c9fb0e8670da4509e9d09d5bab0d2cf67eb4aef015bd7c766f7125195bde6791")
    ]
)