// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see library/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformLibrary",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformLibrary", targets: ["FeastMultiplatformLibrary"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformLibrary",
            url: "https://github.com/guardian/feast-multiplatform-library/releases/download/18.0.0/FeastMultiplatformLibrary.xcframework.zip",
            checksum:"31a10e178d6296bcc1efa785c1f90d91f1753dcc521e6b8229b7a736af9c18d1")
    ]
)