// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see backend/api/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformBackend",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformBackend", targets: ["FeastMultiplatformBackend"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformBackend",
            url: "https://github.com/guardian/feast-multiplatform-library/releases/download/2.0.0/FeastMultiplatformBackend.xcframework.zip",
            checksum:"b8dc3d930c86fdb4d93ee066d684bf4c421e040fd860b6888ee4a884d2cc2a1a")
    ]
)