// swift-tools-version:5.9
// This file is automatically generated by the Gradle build.
// Do not edit manually - see backend/api/build.gradle.kts for the generation logic.
import PackageDescription

let package = Package(
    name: "FeastMultiplatformBackend",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "FeastMultiplatformBackend", targets: ["FeastMultiplatformBackend"])
    ],
    targets: [
        .binaryTarget(
            name: "FeastMultiplatformBackend",
            url: "https://github.com/guardian/feast-multiplatform-library/releases/download/2.0.0/FeastMultiplatformBackend.xcframework.zip",
            checksum:"66c32e4c11c55f1fd31a193d08193d0be4e75f1bd00d915c75405abcc3559cd5")
    ]
)