#!/usr/bin/env python3

import csv
import json
import logging
import os
import sys
from argparse import ArgumentParser
from datetime import datetime

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

### START MAIN
parser = ArgumentParser()
parser.add_argument("--input", "-i", type=str, help="input CSV file")
parser.add_argument("--output", "-o", type=str, default="output.json", help="JSON file to output")
parser.add_argument("--with-source", action="store_true", help="also overwrite the generated source file of the data fixture")
args = parser.parse_args()

if args.input is None:
    logger.error("You must specify an input file. Use --help to see the options.")
    sys.exit(1)

terminology_map = {}
with open(args.input) as f:
    reader = csv.reader(f)
    for idx, row in enumerate(reader):
        try:
            if idx == 0:
                logger.info(f"Skipping possible header row {row}")
                continue
            if len(row) != 3:
                raise ValueError("Row must have exactly 3 columns: id, ukTerm, and usTerm")
            id, uk_term, us_term = row
            terminology_map[(id.strip(), uk_term.strip(), us_term.strip())] = [id.strip(), uk_term.strip(), us_term.strip()]
        except ValueError as e:
            logger.warning(f"Could not parse row {idx}: {e}")


if not terminology_map:
    logger.error("No valid terminology entries found in the input file.")
    sys.exit(1)

logger.info(f"Loaded {len(terminology_map)} terminology entries")

# result = {
#     'prepared_at': datetime.now().isoformat(),
#     'terminology': terminology_map
# }
result = {
    'prepared_at': datetime.now().isoformat(),
    'key': ['id', 'ukTerm', 'usTerm'],
    'values': [[id, ukTerm, usTerm] for (id, ukTerm, usTerm) in terminology_map.keys() if len((id, ukTerm, usTerm)) == 3]
}

with open(args.output, "w") as f:
    f.write(json.dumps(result, separators=(',', ':')))

if args.with_source:
    mypath = os.path.abspath(os.path.dirname(__file__))
    target_path = os.path.abspath(os.path.join(mypath, "..", "library", "src", "commonMain", "kotlin", "com", "gu", "recipe", "generated"))

    if not os.path.exists(target_path):
        logger.error(f"Cannot write source data, as the destination path {target_path} does not exist. Check that you are running from the right directory.")
        sys.exit(2)
    target = os.path.join(target_path, "TerminologyFixture.kt")

    with open(target, "w") as f:
        f.write("// THIS SOURCE FILE IS GENERATED BY process-terminology-csv.py. DON'T EDIT MANUALLY\n")
        f.write("package com.gu.recipe.generated\n\n")
        # f.write(f"val internalTerminologyData = \"\"\"{json.dumps(terminology_map, separators=(',', ':'))}\"\"\"")
        f.write(f"val internalTerminologyData = \"\"\"{json.dumps(result, separators=(',', ':'))}\"\"\"")