#!/usr/bin/env python3

import csv
import argparse

### START MAIN
parser = argparse.ArgumentParser(description="Generate a report of linkable recipes based on the output of find_convertible_recipes.py")
parser.add_argument('--input', help="The CSV file generated by find_convertible_recipes.py")
parser.add_argument('--out', help='html to write', default='links.html')
args = parser.parse_args()

with open(args.input, 'r') as f:
    reader = csv.reader(f)
    linkable_recipes = [row for row in reader]  # Only include recipes with potentially missing keys

with open(args.out, 'w') as f:
    f.write('<html><head><title>Linkable Recipes Report</title></head><body>')
    f.write('<h1>Linkable Recipes Report</h1>')
    f.write(f'<p>Total linkable recipes: {len(linkable_recipes)}</p>')
    f.write('<table border="1"><tr><th>Link</th><th>Title</th><th>Has Missing Keys</th></tr>')
    for csid, uid, title, has_missing_keys in linkable_recipes:
        f.write(f'<tr><td>' +
                f'<a href="https://drkcy8k8qq6jt.cloudfront.net/content/{uid}?debug=1&units=us#ingredients" target="_blank">https://drkcy8k8qq6jt.cloudfront.net/content/{uid}</a>' +
                f'</td><td>{title}</td><td>{has_missing_keys}</td></tr>')
    f.write('</table></body></html>')